---
title: C28105 | Documentos de Microsoft
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology:
- vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
caps.latest.revision: 
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload:
- multiple
ms.openlocfilehash: 21b1f4923621105f84ea8dca78fb31006fffde49
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 12/22/2017
---
# <a name="c28105"></a>C28105
Advertencia C28105: Pérdida de recursos debido a una excepción  
  
 El recurso especificado no se libera cuando se produce una excepción. La instrucción especificada por la ruta de acceso puede producir una excepción. Esta advertencia es similar a la advertencia [C28103](../code-quality/c28103.md), salvo que en este caso está implicada una excepción.  
  
## <a name="example"></a>Ejemplo  
 El siguiente código de ejemplo genera esta advertencia:  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 El siguiente código de ejemplo evita esta advertencia:  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```