---
title: "C28105 | Microsoft Docs"
ms.custom: ""
ms.date: "12/05/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C28105"
helpviewer_keywords: 
  - "C28105"
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
caps.latest.revision: 3
caps.handback.revision: 3
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
---
# C28105
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

Advertencia C28105: Recurso con pérdidas debido a una excepción  
  
 No se libera el recurso especificado cuando se produce una excepción.  La instrucción especificada en la ruta de acceso puede provocar una excepción.  Esta advertencia es similar a [C28103](../code-quality/c28103.md), salvo que en este caso una excepción está implicada.  
  
## Ejemplo  
 El siguiente ejemplo de código genera la advertencia:  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 El siguiente ejemplo de código evita la advertencia:  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```